### ISSUE TITLE
Add dropdown menu to waypoint trajectory

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr_blockly#20]
![image](https://cloud.githubusercontent.com/assets/3330595/23411410/1d30db4e-fdca-11e6-89a5-1e907a5d6c17.png)

So I don't need to know the name of my waypoint.

**Comment by AndriyPt** [comment]
This functionality is already implemented. But in order to get dropdown working the following service need to be running **list_robot_states** service. Which is part of **warehouse_services** where robot states are stored. 
*Although it is limited to [hardcoded list of robots](https://github.com/shadow-robot/sr_blockly/blob/master/sr_blockly_blocks/blocks/trajectory_named_waypoint.js#L29)*
